var data = [
  {
    "ContactID": 4492664,
    "ContactGUID": "6579625C-AC2D-4508-B1C4-98EB50F8A200",
    "SourceApplication": "rohitChauhan3",
    "ContactImage": null,
    "IsDefaultEmail": true,
    "Title": null,
    "Prefix": null,
    "DisplayName": "Betty White",
    "FirstName": "Betty",
    "MiddleName": null,
    "LastName": "White",
    "Suffix": null,
    "DateOfBirth": "1984-03-14T00:00:00",
    "Gender": "Z",
    "CountryCode": 1,
    "DoNotEmail": true,
    "DoNotCall": false,
    "Note": "Any special Comments",
    "CreateBy": 1201,
    "CreateDate": "0001-01-01T00:00:00",
    "ModifyBy": 1201,
    "ModifyDate": "0001-01-01T00:00:00",
    "FacebookUserId": null,
    "GoogleUserId": null,
    "HasConfirmedContactInfo": false,
    "EmailAddress": "rohit@rohit16.com",
    "ContactTypes": [
      {
        "ContactTypeID": 3,
        "ContactTypeName": "Customer"
      }
    ],
    "Relationships": [
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Spouse",
        "RelationshipTypeDescription": "Spouse"
      },
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Parent",
        "RelationshipTypeDescription": "Parent"
      }
    ],
    "Phones": [
      {
        "PhoneGUID": "6E083E95-0143-4254-8864-AD6DA745968D",
        "CountryCode": "+1",
        "PhoneNo": "817-504-3232",
        "Extension": null,
        "DNCFederal": false,
        "DNCState": false,
        "DNCSolarcity": false,
        "PhoneType": "Other",
        "PhoneTypeDescription": "Other",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "3289D297-3488-4BBF-AC73-AEB535AA70E3",
        "CountryCode": "US3",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "1DDD6867-1426-46C3-BF77-03B040BD59A4",
        "CountryCode": "US2",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "4C811465-30BC-402A-AF7F-978D9E3B4977",
        "CountryCode": "US4",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "5DBD2072-B8CB-497C-855E-C6105BF8B44C",
        "CountryCode": "US6",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      }
    ],
    "Addresses": [
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "704 Benvenue AvenueLos AltosCA94024SANTA CLARAUS",
        "AddressLine1": "704 Benvenue Avenue",
        "AddressLineTwo": "",
        "City": "Los Altos",
        "County": "SANTA CLARA",
        "Country": "US",
        "PostalCode": "94024",
        "Latitude": 37.3746020000,
        "Longitude": -122.0995850000,
        "AddressTypeID": 4,
        "isSameAsInstallAddress": true,
        "AddressId": 20090297,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "4AEC7549-CB6D-4C5A-872A-1BCF74E926C8",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Billing",
        "AddressTypeDescription": "Billing"
      },
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "171 E Floresta WayPortola ValleyCA94028SAN MATEOUS",
        "AddressLine1": "171 E Floresta Way",
        "AddressLineTwo": "",
        "City": "Portola Valley",
        "County": "SAN MATEO",
        "Country": "US",
        "PostalCode": "94028",
        "Latitude": 37.4012760000,
        "Longitude": -122.1958870000,
        "AddressTypeID": 5,
        "isSameAsInstallAddress": true,
        "AddressId": 20090298,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "F0C766B8-B0E5-4048-8B56-4134E49AF339",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Mailing",
        "AddressTypeDescription": "Mailing"
      }
    ]
  },
  {
    "ContactID": 4111111,
    "ContactGUID": "6579625C-AC2D-4508-B1C4-98EB50F8A200",
    "SourceApplication": "rohitChauhan3",
    "ContactImage": null,
    "IsDefaultEmail": true,
    "Title": null,
    "Prefix": null,
    "DisplayName": "Roger White",
    "FirstName": "Roger",
    "MiddleName": null,
    "LastName": "White",
    "Suffix": null,
    "DateOfBirth": "1984-03-14T00:00:00",
    "Gender": "Z",
    "CountryCode": 1,
    "DoNotEmail": true,
    "DoNotCall": false,
    "Note": "Any special Comments",
    "CreateBy": 1201,
    "CreateDate": "0001-01-01T00:00:00",
    "ModifyBy": 1201,
    "ModifyDate": "0001-01-01T00:00:00",
    "FacebookUserId": null,
    "GoogleUserId": null,
    "HasConfirmedContactInfo": false,
    "EmailAddress": "rohit@rohit16.com",
    "ContactTypes": [
      {
        "ContactTypeID": 3,
        "ContactTypeName": "Customer"
      }
    ],
    "Relationships": [
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Spouse",
        "RelationshipTypeDescription": "Spouse"
      },
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Parent",
        "RelationshipTypeDescription": "Parent"
      }
    ],
    "Phones": [
      {
        "PhoneGUID": "6E083E95-0143-4254-8864-AD6DA745968D",
        "CountryCode": "+1",
        "PhoneNo": "817-504-3232",
        "Extension": null,
        "DNCFederal": false,
        "DNCState": false,
        "DNCSolarcity": false,
        "PhoneType": "Other",
        "PhoneTypeDescription": "Other",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "3289D297-3488-4BBF-AC73-AEB535AA70E3",
        "CountryCode": "US3",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "1DDD6867-1426-46C3-BF77-03B040BD59A4",
        "CountryCode": "US2",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "4C811465-30BC-402A-AF7F-978D9E3B4977",
        "CountryCode": "US4",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "5DBD2072-B8CB-497C-855E-C6105BF8B44C",
        "CountryCode": "US6",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      }
    ],
    "Addresses": [
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "704 Benvenue AvenueLos AltosCA94024SANTA CLARAUS",
        "AddressLine1": "704 Benvenue Avenue",
        "AddressLineTwo": "",
        "City": "Los Altos",
        "County": "SANTA CLARA",
        "Country": "US",
        "PostalCode": "94024",
        "Latitude": 37.3746020000,
        "Longitude": -122.0995850000,
        "AddressTypeID": 4,
        "isSameAsInstallAddress": true,
        "AddressId": 20090297,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "4AEC7549-CB6D-4C5A-872A-1BCF74E926C8",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Billing",
        "AddressTypeDescription": "Billing"
      },
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "171 E Floresta WayPortola ValleyCA94028SAN MATEOUS",
        "AddressLine1": "171 E Floresta Way",
        "AddressLineTwo": "",
        "City": "Portola Valley",
        "County": "SAN MATEO",
        "Country": "US",
        "PostalCode": "94028",
        "Latitude": 37.4012760000,
        "Longitude": -122.1958870000,
        "AddressTypeID": 5,
        "isSameAsInstallAddress": true,
        "AddressId": 20090298,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "F0C766B8-B0E5-4048-8B56-4134E49AF339",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Mailing",
        "AddressTypeDescription": "Mailing"
      }
    ]
  },
  {
    "ContactID": 4222222,
    "ContactGUID": "6579625C-AC2D-4508-B1C4-98EB50F8A200",
    "SourceApplication": "rohitChauhan3",
    "ContactImage": null,
    "IsDefaultEmail": true,
    "Title": null,
    "Prefix": null,
    "DisplayName": "James White",
    "FirstName": "James",
    "MiddleName": null,
    "LastName": "White",
    "Suffix": null,
    "DateOfBirth": "1984-03-14T00:00:00",
    "Gender": "Z",
    "CountryCode": 1,
    "DoNotEmail": true,
    "DoNotCall": false,
    "Note": "Any special Comments",
    "CreateBy": 1201,
    "CreateDate": "0001-01-01T00:00:00",
    "ModifyBy": 1201,
    "ModifyDate": "0001-01-01T00:00:00",
    "FacebookUserId": null,
    "GoogleUserId": null,
    "HasConfirmedContactInfo": false,
    "EmailAddress": "rohit@rohit16.com",
    "ContactTypes": [
      {
        "ContactTypeID": 3,
        "ContactTypeName": "Customer"
      }
    ],
    "Relationships": [
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Spouse",
        "RelationshipTypeDescription": "Spouse"
      },
      {
        "ContactName": "B LynetteBoston",
        "RelationContactName": "B LynetteBoston",
        "RelationshipType": "Parent",
        "RelationshipTypeDescription": "Parent"
      }
    ],
    "Phones": [
      {
        "PhoneGUID": "6E083E95-0143-4254-8864-AD6DA745968D",
        "CountryCode": "+1",
        "PhoneNo": "817-504-3232",
        "Extension": null,
        "DNCFederal": false,
        "DNCState": false,
        "DNCSolarcity": false,
        "PhoneType": "Other",
        "PhoneTypeDescription": "Other",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "3289D297-3488-4BBF-AC73-AEB535AA70E3",
        "CountryCode": "US3",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "1DDD6867-1426-46C3-BF77-03B040BD59A4",
        "CountryCode": "US2",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "4C811465-30BC-402A-AF7F-978D9E3B4977",
        "CountryCode": "US4",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      },
      {
        "PhoneGUID": "5DBD2072-B8CB-497C-855E-C6105BF8B44C",
        "CountryCode": "US6",
        "PhoneNo": "A-B-C",
        "Extension": "D",
        "DNCFederal": true,
        "DNCState": true,
        "DNCSolarcity": true,
        "PhoneType": "Home",
        "PhoneTypeDescription": "Home",
        "isPreferredPhone": true,
        "ContactPreferenceNote": null
      }
    ],
    "Addresses": [
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "704 Benvenue AvenueLos AltosCA94024SANTA CLARAUS",
        "AddressLine1": "704 Benvenue Avenue",
        "AddressLineTwo": "",
        "City": "Los Altos",
        "County": "SANTA CLARA",
        "Country": "US",
        "PostalCode": "94024",
        "Latitude": 37.3746020000,
        "Longitude": -122.0995850000,
        "AddressTypeID": 4,
        "isSameAsInstallAddress": true,
        "AddressId": 20090297,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "4AEC7549-CB6D-4C5A-872A-1BCF74E926C8",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Billing",
        "AddressTypeDescription": "Billing"
      },
      {
        "IsActive": true,
        "IsStandardAddress": false,
        "FormattedStreetAddress": "171 E Floresta WayPortola ValleyCA94028SAN MATEOUS",
        "AddressLine1": "171 E Floresta Way",
        "AddressLineTwo": "",
        "City": "Portola Valley",
        "County": "SAN MATEO",
        "Country": "US",
        "PostalCode": "94028",
        "Latitude": 37.4012760000,
        "Longitude": -122.1958870000,
        "AddressTypeID": 5,
        "isSameAsInstallAddress": true,
        "AddressId": 20090298,
        "Label": null,
        "SubLabel": null,
        "AddressGUID": "F0C766B8-B0E5-4048-8B56-4134E49AF339",
        "IsGeoCoded": null,
        "IsGeoCodeOverride": null,
        "AddressType": "Mailing",
        "AddressTypeDescription": "Mailing"
      }
    ]
  }
];
